# Generated by Landing Zone Configurator (export v1). Edit via the Configurator.
company_code = "luk"

company_name = "Lukas Dev GmbH"

labels = {
  "managed_by" = "opentofu"
}

landing_zones = {
  "test-01" = {
    "corporate" = false
    "env" = "dev"
    "owner_email" = "lukas@klue.de"
    "project_code" = "tst01"
    "project_name" = "Test Projekt 1"
    "secretsmanager_enabled" = true
  }
}

organization_id = "0a753513-13fb-46f4-a316-3eccbe84334c"

owner_email = "lukas@klue.de"

region = "eu01"

sandboxes = [
  {
    "project_name" = "Test Sandbox 1"
    "project_owner_email" = "lukas@klue.de"
  },
]
