# Generated by Landing Zone Configurator (export v1). Edit via the Configurator.
company_code = "luk"

company_name = "Lukas Dev GmbH"

labels = {
  "managed_by" = "opentofu"
}

landing_zones = {
  "luk01" = {
    "corporate" = false
    "env" = "dev"
    "owner_email" = "lukas.weberruss@digits.schwarz"
    "project_code" = "tst"
    "project_name" = "Luk Projekt 1"
    "secretsmanager_enabled" = true
  }
}

organization_id = "af026540-93fd-4712-a772-25a35fec24d4"

owner_email = "lukas.weberruss@digits.schwarz"

region = "eu01"

sandboxes = [
  {
    "project_name" = "Luk Sandbox 1"
    "project_owner_email" = "lukas.weberruss@digits.schwarz"
  },
]
