# Generated by Landing Zone Configurator (export v1). Edit via the Configurator.
company_code = "lzc-dev"

company_name = "Landing Zone Dev Configurator"

firewall_config = null

labels = {
  "managed_by" = "opentofu"
}

landing_zone_namespace_services = {}

landing_zones = {}

organization_id = "af026540-93fd-4712-a772-25a35fec24d4"

organization_owners = [
  "lukas.weberruss@digits.cloud",
]

owner_email = "lukas.weberruss@digits.cloud"

region = "eu01"

rm_folders = {
  "landing_zones_corporate" = {
    "description" = null
    "name" = "Corporate - Dev Configurator"
    "owner_emails" = []
    "reader_emails" = []
  }
  "landing_zones_public" = {
    "description" = null
    "name" = "Public - Dev Configurator"
    "owner_emails" = []
    "reader_emails" = []
  }
  "platform" = {
    "description" = null
    "name" = "Platform - Dev Configurator"
    "owner_emails" = []
    "reader_emails" = []
  }
  "sandboxes" = {
    "description" = null
    "name" = "Sandboxes - Dev Configurator"
    "owner_emails" = []
    "reader_emails" = []
  }
}

sandboxes = []
